# Generated by Django 4.1.5 on 2023-01-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUMDOSVERLING', models.CharField(max_length=255, verbose_name='NUMDOSVERLING')),
                ('ANCART', models.CharField(max_length=255, verbose_name='ANCART')),
                ('FILIERE', models.CharField(max_length=255, verbose_name='FILIERE')),
                ('ETAPE', models.IntegerField(verbose_name='ETAPE')),
                ('VERLING', models.CharField(max_length=255, verbose_name='VERLING')),
                ('NUMDOS', models.CharField(max_length=255, verbose_name='NUMDOS')),
                ('FORMAT', models.CharField(max_length=255, verbose_name='FORMAT')),
            ],
        ),
    ]
